apiVersion: v1
kind: Service

metadata:
    name: wpsvc
spec: 
    type: NodePort
    selector:
        app: wordpressapp
    ports:
       - targetPort: 80
         port: 80
         nodePort: 30000

